### ISSUE TITLE
Suporte da GuaraTeca para a Ponte H Dupla L9110 (HG7881)

### ISSUE THREAD

**Issue by Rosiberto** [JoaquimFlavio/GuaraTeca_OBR#2]
Olá Joaquim,

Incluir suporte para a Ponte H L9110 (HG7881) na GuaraTeca_OBR. 

Essa Ponte H não possui o pino de controle de velocidade, o que impede que a GuaraTeca consiga controlar a velocidade dos motores.

Att,

**Comment by JoaquimFlavio** [comment]
Boa tarde.

Agradecemos pelo seu contato. Realmente foi verificado que esse modulo de controle de motor é incompatível com a versão atual da GuaraTeca!
Estaremos trabalhando para fornecer suporte a esse modulo.

Att Joaquim Flavio

**Comment by JoaquimFlavio** [comment]
Agora a GuaraTeca possui suporte a este drive de motor!
