### ISSUE TITLE
Ajuste na Correção de Velocidade das Classes HRobot e HGRobot

### ISSUE THREAD

**Issue by Rosiberto** [JoaquimFlavio/GuaraTeca_OBR#3]
O if da velocidade quando o usuário informar um valor menor que ZERO.

 //Correcão de possíveis erros de usuario.
    if(velocidade > 100)
        velocidade = 100;
    **else if(velocidade < 100)**
        velocidade = 0;

**Comment by JoaquimFlavio** [comment]
Boa noite.

Agradecemos o contato! O problema ja está corrigido!

Att Joaquim Flávio
