### ISSUE TITLE
Ajuste no Motor Direito nas funções (direita, esquerda, frente e tras)

### ISSUE THREAD

**Issue by Rosiberto** [JoaquimFlavio/GuaraTeca_OBR#4]
As funções HGRobot:: (frente , tras, direita, esquerda)

Na linha antes do if que adiciona a velocidade do motor direito, está setado ambas as portas a mesma posição do array.

    sentido1_L9110(motor[0], motor[1], this->VME);
    sentido1_L9110(**motor[2], motor[2]**, this->VMD);

ajustar para:
    sentido1_L9110(motor[0], motor[1], this->VME);
   sentido1_L9110(**motor[2], motor[3]**, this->VMD);

**Comment by JoaquimFlavio** [comment]
Boa noite.

Agradecemos o contato! O problema ja está corrigido!

Att Joaquim Flávio
